- name: Reset User Passwords
  hosts: servers
  become: yes
  tasks:
    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ new_pass | password_hash('sha512') }}"
